apiVersion: v1
data:
  AWS_ID: QUtJQVlJMlNVM0U0RFVTSU9DT08=
  AWS_KEY: d1c5V1JOL0grTFZ2VWQwejZkN1g0N0ZNSDk3L3pXSTAzcXRCTnJHZQ==
kind: Secret
metadata:
  creationTimestamp: "2025-10-21T10:09:17Z"
  name: aws-secret
  namespace: devops
  resourceVersion: "131771390"
  uid: 82a05ed1-5229-4eee-9c34-b4976a3caf7a
type: Opaque
