apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJsb2NhbGhvc3Q6MzAwMCI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZRV1J0YVc0aE1qTT0iCgkJfQoJfQp9
kind: Secret
metadata:
  creationTimestamp: "2025-07-01T08:07:53Z"
  name: auth
  namespace: devops
  resourceVersion: "106355736"
  uid: bed0c4b7-b8aa-43e7-8729-680ed77124a5
type: kubernetes.io/dockerconfigjson
